// <auto-generated />
using System;
using Infrastructure.Data.Postgreesql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Postgreesql.Migrations
{
    [DbContext(typeof(TILTContext))]
    [Migration("20260518120000_CreateRefundTransactionsTable")]
    partial class CreateRefundTransactionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tilt")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("Sequence-DriverTransfers")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Orders")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Payments")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-RefundTransactions")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Users")
                .IncrementsBy(10);

            modelBuilder.Entity("Domain.Features.Orders.Entities.Message", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(4);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<long>("SourceUserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<long>("TargetUserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(3);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(5);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.HasIndex("SourceUserId");

                b.HasIndex("TargetUserId");

                b.ToTable("Messages", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Order", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-Orders");

                b.Property<DateTime?>("AcceptanceTime")
                    .HasColumnType("timestamp")
                    .HasColumnName("AcceptanceTime")
                    .HasColumnOrder(8);

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric")
                    .HasColumnName("Amount")
                    .HasColumnOrder(4);

                b.Property<string>("CancelDescription")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("CancelDescription")
                    .HasColumnOrder(13);

                b.Property<string>("CancelRasons")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("CancelRasons")
                    .HasColumnOrder(14);

                b.Property<DateTime?>("CancelationTime")
                    .HasColumnType("timestamp")
                    .HasColumnName("CancelationTime")
                    .HasColumnOrder(10);

                b.Property<DateTime?>("CompletionTime")
                    .HasColumnType("timestamp")
                    .HasColumnName("CompletionTime")
                    .HasColumnOrder(9);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(5);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<int>("DistanceInKM")
                    .HasColumnType("integer");

                b.Property<long?>("DriverId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<int>("DurationInSeconds")
                    .HasColumnType("integer");

                b.Property<string>("Notes")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("Notes")
                    .HasColumnOrder(12);

                b.Property<string>("PaymentId")
                    .HasColumnType("text");

                b.Property<Point>("Point")
                    .IsRequired()
                    .HasColumnType("geography(POINT, 4326)")
                    .HasColumnName("Location");

                b.Property<DateTime?>("RequestedTime")
                    .HasColumnType("timestamp")
                    .HasColumnName("RequestedTime")
                    .HasColumnOrder(7);

                b.Property<DateTime?>("ScheduleTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("Status")
                    .HasColumnOrder(3);

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("Type")
                    .HasColumnOrder(11);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(6);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.HasKey("Id");

                b.HasIndex("DriverId");

                b.HasIndex("UserId");

                b.ToTable("Orders", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Rate", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(4);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<string>("Description")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("Description")
                    .HasColumnOrder(6);

                b.Property<long>("OrderId")
                    .HasColumnType("bigint");

                b.Property<long>("SourceUserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<string>("Tags")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("Tags")
                    .HasColumnOrder(7);

                b.Property<long>("TargetUserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(5);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<float>("Value")
                    .HasColumnType("real")
                    .HasColumnName("Value")
                    .HasColumnOrder(3);

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.HasIndex("SourceUserId");

                b.HasIndex("TargetUserId");

                b.ToTable("Rates", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Rejection", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(3);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("DriverId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<long>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(4);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("DriverId");

                b.HasIndex("OrderId");

                b.ToTable("Rejections", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.RefundTransaction", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-RefundTransactions");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric")
                    .HasColumnName("Amount")
                    .HasColumnOrder(3);

                b.Property<string>("AsaasTransferId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("AsaasTransferId")
                    .HasColumnOrder(8);

                b.Property<string>("CustomerWalletId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("CustomerWalletId")
                    .HasColumnOrder(4);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint")
                    .HasColumnOrder(10);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(9);

                b.Property<string>("ErrorDetails")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("ErrorDetails")
                    .HasColumnOrder(7);

                b.Property<long>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<int>("RetryCount")
                    .HasColumnType("integer")
                    .HasColumnName("RetryCount")
                    .HasColumnOrder(6);

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("Status")
                    .HasColumnOrder(5);

                b.Property<Guid>("TransactionId")
                    .HasColumnType("uuid")
                    .HasColumnName("TransactionId")
                    .HasColumnOrder(1);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnOrder(12);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(11);

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.HasIndex("TransactionId");

                b.ToTable("RefundTransactions", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Tracking", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(3);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<Point>("Point")
                    .IsRequired()
                    .HasColumnType("geography(POINT, 4326)")
                    .HasColumnName("Location")
                    .HasColumnOrder(2);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(4);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("Trackings", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Payments.Entities.DriverTransfer", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-DriverTransfers");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric")
                    .HasColumnName("Amount")
                    .HasColumnOrder(3);

                b.Property<string>("AsaasTransferId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("AsaasTransferId")
                    .HasColumnOrder(5);

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("CompletedAt")
                    .HasColumnOrder(6);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(7);

                b.Property<long>("DriverId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("ErrorMessage")
                    .HasColumnOrder(8);

                b.Property<DateTime?>("FailedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("FailedAt")
                    .HasColumnOrder(7);

                b.Property<long>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("Status")
                    .HasColumnOrder(4);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated");

                b.HasKey("Id");

                b.HasIndex("DriverId");

                b.HasIndex("OrderId");

                b.ToTable("DriverTransfers", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Payments.Entities.Payment", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-Payments");

                b.Property<DateTime?>("ApprovedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("ApprovedAt");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric")
                    .HasColumnName("Amount");

                b.Property<string>("AsaasPaymentId")
                    .HasColumnType("text")
                    .HasColumnName("AsaasPaymentId");

                b.Property<DateTime?>("CancelledAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("CancelledAt");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("CreatedAt");

                b.Property<long?>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnName("OrderId");

                b.Property<string>("PixLink")
                    .HasColumnType("text")
                    .HasColumnName("PixLink");

                b.Property<string>("PixQrCode")
                    .HasColumnType("text")
                    .HasColumnName("PixQrCode");

                b.Property<long>("ReceiverId")
                    .HasColumnType("bigint");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("Status");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("Type");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("UpdatedAt");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("AsaasPaymentId");

                b.HasIndex("OrderId");

                b.HasIndex("ReceiverId");

                b.HasIndex("UserId");

                b.ToTable("Payments", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Plans.Entities.Plan", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(3);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<string>("Description")
                    .HasColumnType("varchar(500)")
                    .HasColumnName("Description")
                    .HasColumnOrder(2);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar(250)")
                    .HasColumnName("Name")
                    .HasColumnOrder(1);

                b.Property<decimal>("Price")
                    .HasColumnType("numeric")
                    .HasColumnName("Price")
                    .HasColumnOrder(4);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(5);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("Plans", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Subscriptions.Entities.Subscription", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("AsaasPaymentId")
                    .HasColumnType("text");

                b.Property<string>("AsaasPaymentLink")
                    .HasColumnType("text");

                b.Property<string>("AsaasSubscriptionId")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(3);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("PlanId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(1);

                b.Property<DateTime?>("PaidAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("SubscriptionType")
                    .HasColumnType("integer");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated")
                    .HasColumnOrder(4);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnOrder(2);

                b.HasKey("Id");

                b.HasIndex("PlanId");

                b.HasIndex("UserId");

                b.ToTable("Subscriptions", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-Users");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(13);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<string>("Document")
                    .IsRequired()
                    .HasColumnType("character varying(11)")
                    .HasMaxLength(11)
                    .HasColumnName("Document")
                    .HasColumnOrder(4);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("Email")
                    .HasColumnOrder(5);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("Name")
                    .HasColumnOrder(1);

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("Password")
                    .HasColumnOrder(3);

                b.Property<string>("Photo")
                    .HasColumnType("character varying(1000)")
                    .HasMaxLength(1000)
                    .HasColumnName("Photo")
                    .HasColumnOrder(7);

                b.Property<string>("ValidationCode")
                    .HasColumnType("character varying(6)")
                    .HasMaxLength(6)
                    .HasColumnName("ValidationCode")
                    .HasColumnOrder(6);

                b.Property<string>("ValidationSalt")
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("ValidationSalt")
                    .HasColumnOrder(15);

                b.Property<string>("VehicleModel")
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("VehicleModel")
                    .HasColumnOrder(10);

                b.Property<string>("VehiclePlate")
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("VehiclePlate")
                    .HasColumnOrder(11);

                b.Property<short?>("VehicleYear")
                    .HasColumnType("smallint")
                    .HasColumnName("VehicleYear")
                    .HasColumnOrder(12);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint")
                    .HasColumnOrder(14);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated");

                b.Property<string>("PaymentToken")
                    .HasColumnType("character varying(1000)")
                    .HasMaxLength(1000)
                    .HasColumnName("PaymentToken")
                    .HasColumnOrder(16);

                b.Property<string>("Description")
                    .HasColumnType("character varying(250)")
                    .HasMaxLength(250)
                    .HasColumnName("Description")
                    .HasColumnOrder(17);

                b.HasKey("Id");

                b.ToTable("Users", "tilt");
            });

            modelBuilder.Entity("Infrastructure.Data.Postgreesql.Features.Security.Entities.RefreshTokens", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Created")
                    .HasColumnOrder(3);

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("ExpiresAt")
                    .HasColumnOrder(2);

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("character varying(500)")
                    .HasColumnName("Token")
                    .HasColumnOrder(1);

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp")
                    .HasColumnName("Updated");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("RefreshTokens", "tilt");
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Message", b =>
            {
                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("SourceUserId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("TargetUserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Order", b =>
            {
                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("DriverId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Rate", b =>
            {
                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("SourceUserId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("TargetUserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Rejection", b =>
            {
                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("DriverId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.RefundTransaction", b =>
            {
                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Orders.Entities.Tracking", b =>
            {
                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Payments.Entities.DriverTransfer", b =>
            {
                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("DriverId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Domain.Features.Payments.Entities.Payment", b =>
            {
                b.HasOne("Domain.Features.Orders.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("ReceiverId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Domain.Features.Subscriptions.Entities.Subscription", b =>
            {
                b.HasOne("Domain.Features.Plans.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Infrastructure.Data.Postgreesql.Features.Security.Entities.RefreshTokens", b =>
            {
                b.HasOne("Domain.Features.Users.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}