// <auto-generated />
using System;
using Infrastructure.Data.Postgreesql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Postgreesql.Migrations
{
    [DbContext(typeof(TILTContext))]
    [Migration("20260509175600_CreatePaymentsTable")]
    partial class CreatePaymentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tilt")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("Sequence-DriverTransfers")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Orders")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Payments")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Sequence-Users")
                .IncrementsBy(10);

            modelBuilder.Entity("Domain.Features.Payments.Entities.Payment", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "Sequence-Payments");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric")
                    .HasColumnName("Amount");

                b.Property<DateTime?>("ApprovedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("ApprovedAt");

                b.Property<string>("AsaasPaymentId")
                    .HasColumnType("text")
                    .HasColumnName("AsaasPaymentId");

                b.Property<DateTime?>("CancelledAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("CancelledAt");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<Guid?>("Identifier")
                    .HasColumnType("uuid");

                b.Property<long?>("OrderId")
                    .HasColumnType("bigint")
                    .HasColumnName("OrderId");

                b.Property<string>("PixLink")
                    .HasColumnType("text")
                    .HasColumnName("PixLink");

                b.Property<string>("PixQrCode")
                    .HasColumnType("text")
                    .HasColumnName("PixQrCode");

                b.Property<long>("ReceiverId")
                    .HasColumnType("bigint");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("Status");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("Type");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("AsaasPaymentId");

                b.HasIndex("OrderId");

                b.HasIndex("ReceiverId");

                b.HasIndex("UserId");

                b.ToTable("Payments", "tilt");
            });
#pragma warning restore 612, 618
        }
    }
}